manifest:
  version: "0.13"

  self:
    path: zephyr-app

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.4.0
      import: true       # pulls in all of Zephyr's own west.yml modules

  defaults:
    remote: zephyrproject
